# Generated by Django 6.1.1 on 2026-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StationRecord",
            fields=[
                ("station_id", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=32)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("address", models.CharField(max_length=255)),
                ("post_code", models.CharField(max_length=16)),
                ("rental_methods", models.JSONField(default=list)),
                ("capacity", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
