# Generated by Django 6.1.1 on 2026-09-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderecord',
            name='distance_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
