# Generated by Django 6.1.1 on 2026-09-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0002_riderecord_distance_checked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderecord",
            name="weather_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
